spring.application.name=db-zapatillas

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Base de Datos (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6nvmsa4d50c738hg4k0-a.frankfurt-postgres.render.com:5432/tienda_zapas
spring.datasource.username=admin
spring.datasource.password=ys3ttOs7M14Xeh5hI6ylMZNhmsJXG3Wi
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=10000